version: "3.9"

services:

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jobportaldb

    ports:
      - "3308:3306"

    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: ./JobPortal Backend/JobPortal
    container_name: jobportal-backend

    ports:
      - "8080:8080"

    depends_on:
      - mysql

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/jobportaldb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}

      GEMINI_API_KEY: ${GEMINI_API_KEY}

      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}

  frontend:
    build: ./jobportal-frontend
    container_name: jobportal-frontend

    ports:
      - "5173:5173"

    depends_on:
      - backend

volumes:
  mysql-data: